
gates = ["Controlled-X", "Controlled-V", "Controlled-V+"]

circuits = {
    "HNG": [
        ("Controlled-V", (3, 0)),
        ("Controlled-V", (3, 1)),
        ("Controlled-V", (3, 2)),
        ("Controlled-X", (2, 0)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V+", (3, 2))
    ],
    "PFAG": [
        ("Controlled-V", (3, 1)),
        ("Controlled-X", (1, 0)),
        ("Controlled-V", (3, 0)),
        ("Controlled-V", (3, 2)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V+", (3, 2)),
    ],
    "MIG": [
        ("Controlled-X", (3, 1)),
        ("Controlled-V", (3, 1)),
        ("Controlled-V", (2, 1)),
        ("Controlled-V", (3, 0)),
        ("Controlled-V", (2, 0)),
        ("Controlled-X", (1, 0)),
        ("Controlled-V", (3, 1)),
        ("Controlled-V+", (2, 1)),
    ],
    "IG": [
        ("Controlled-V", (2, 1)),
        ("Controlled-V", (2, 0)),
        ("Controlled-X", (1, 0)),
        ("Controlled-V+", (2, 1)),
        ("Controlled-V", (3, 1)),
        ("Controlled-V", (3, 0)),
        ("Controlled-X", (1, 0)),
        ("Controlled-V+", (3, 1)),
        ("Controlled-X", (1, 0)),
    ],
    "OTG": [
        ("Controlled-X", (3, 2)),
        ("Controlled-V", (2, 3)),
        ("Controlled-V", (2, 3)),
        ("Controlled-X", (3, 2)),
        ("Controlled-V", (3, 1)),
        ("Controlled-V", (3, 0)),
        ("Controlled-X", (1, 0)),
        ("Controlled-V", (3, 2)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V+", (3, 2)),
    ],
    "MKG": [
        ("Controlled-X", (0, 3)),
        ("Controlled-V", (1, 0)),
        ("Controlled-V", (1, 3)),
        ("Controlled-X", (0, 3)),
        ("Controlled-V+", (1, 0)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V", (1, 2)),
        ("Controlled-V", (1, 2)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V", (3, 2)),
        ("Controlled-V", (3, 1)),
        ("Controlled-X", (2, 1)),
        ("Controlled-V+", (3, 2)),
        ("Controlled-V", (3, 2)),
        ("Controlled-V", (3, 0)),
        ("Controlled-X", (2, 0)),
        ("Controlled-V+", (3, 2)),
    ],
}